# Generated by Django 3.0.8 on 2020-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200718_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
